---
title: "Final visualizations"
author: "Hilmar Berger"
output: 
 html_document:
    toc: true
    toc_depth: 3
    toc_float: false
    number_sections: true
    code_folding: hide
    
pdf_document:
    fig_caption: true
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
---


```{r, message=FALSE}
rm(list=ls())
library(Seurat)
library(ggplot2)

# library(readxl)
# library(writexl)
library(knitr)
library(data.table)
library(cowplot)
library(magrittr)
library(dplyr)

library(homologene)

library(pheatmap)

library(grid)

result_folder = "../../Results/stromal/"
data_storage_folder = result_folder

library(future)
options("future.globals.maxSize"=2**33)
#plan("multisession", workers = 8)
plan("sequential")

options("save.defaults" = list(compress=TRUE))
```


```{r}
#scData.combined = readRDS(file.path("data", "Colon_Assembloids_SCT_CC_adj_simple_clusters_2023-02-10.rds"))
scData.combined = readRDS(file.path(result_folder, "Assembloids_combined_SCT_CC_adj_annotated.rds"))
```


```{r, fig.width=8, fig.height=6}
scData.combined = SetIdent(scData.combined, value="cluster_label" )
p = DimPlot(scData.combined, reduction = "umap", label = TRUE)
print(p)
```

```{r}
scData.combined$cluster_label = factor(scData.combined$cluster_label, levels=c("Fibroblast A","Fibroblast A/MF","Fibroblast B1","Fibroblast B2","Glia","Endothelial","Neuron"))
scData.combined <- SetIdent(scData.combined, value = "cluster_label")
```


# Fig. 2

## 2c

```{r}
p = DimPlot(scData.combined, label=T, repel=T)
print(p)

pdf(file.path(result_folder, "Fig_2c.pdf"), width = 6, height = 6)
print(p)
dev.off()

```

## Fig 2d

```{r, fig.width=6, fig.height=5}
p = DotPlot(scData.combined, features = c("Col1a2","Pdgfra","Acta2","Tagln","Sox10","S100b","Pecam1","Lyve1","Elavl4","Phox2b","Ano1"), assay = "RNA", cols="RdYlBu") + theme(axis.text.x = element_text(angle=45, hjust=1))
print(p)

pdf(file.path(result_folder, "Fig_2d.pdf"), width = 6, height = 5)
print(p)
dev.off()

```

## Fig 2e

```{r, fig.width=10, fig.height=7}
sel_markers =  c("Foxl1","Wnt5a","Sox6","Cd34","Cd81","Rspo3")
all_plots = list()
for (mm in sel_markers) {
  p = FeaturePlot(scData.combined, features =mm, ncol = 1, order=T, max.cutoff = "q90")  + NoAxes() + theme(legend.key.size = grid::unit(10, "points"))
  all_plots[[mm]] = p
}

cowplot::plot_grid(plotlist = all_plots, nrow=2, ncol=3, greedy = T)

pdf(file.path(result_folder, "Fig_2e.pdf"), width = 10, height = 7)
cowplot::plot_grid(plotlist = all_plots, nrow=2, ncol=3, greedy = T)
dev.off()

```


# Fig 3

## Fig 3a

```{r, fig.width=10, fig.height=5}
sel_markers = c("Grem1","Grem2","Mgp","Chrd","Fst","Nog",paste0("Bmp",1:7))
p = DotPlot(scData.combined, features = sel_markers, assay = "RNA", cols="RdYlBu", dot.scale = 10) + theme(axis.text.x = element_text(angle=45, hjust=1))
print(p)

pdf(file.path(result_folder, "Fig_3a.pdf"), width = 10, height = 5)
print(p)
dev.off()

```

## Fig 3b 

```{r, fig.width=10, fig.height=7}
sel_markers =  c("Bmp2","Bmp5","Bmp7","Grem1","Grem2","Mgp")
all_plots = list()
for (mm in sel_markers) {
  p = FeaturePlot(scData.combined, features =mm, ncol = 1, order=T)  + NoAxes() + theme(legend.key.size = grid::unit(10, "points"))
  all_plots[[mm]] = p
}

cowplot::plot_grid(plotlist = all_plots, nrow=2, ncol=3, greedy = T)

pdf(file.path(result_folder, "Fig_3b.pdf"), width = 10, height = 7)
cowplot::plot_grid(plotlist = all_plots, nrow=2, ncol=3, greedy = T)
dev.off()

```


# Supp Fig. 5

## Supp Fig 5b


```{r, fig.width=7, fig.height=6}
sel_markers =   c("Col1a2","Pdgfra","Acta2","Sox10","Pecam1","S100b")
all_plots = list()
for (mm in sel_markers) {
  p = FeaturePlot(scData.combined, features =mm, ncol = 1, order=T, max.cutoff = "q99")  + NoAxes() + theme(legend.key.size = grid::unit(10, "points"))
  all_plots[[mm]] = p
}

cowplot::plot_grid(plotlist = all_plots, nrow=2, ncol=3, greedy = T)

pdf(file.path(result_folder, "Fig_S5b.pdf"), width = 7, height = 6)
cowplot::plot_grid(plotlist = all_plots, nrow=2, ncol=3, greedy = T)
dev.off()

```

## Supp Fig 5c

```{r, fig.width=10, fig.height=5}
sel_markers = c(paste0("Wnt",c("2","2b","4","5a","5b","6","9a","10a","11")), paste0("Rspo",1:3), "Dkk2","Dkk3","Sfrp1","Sfrp4","Wif1","Frzb")
p = DotPlot(scData.combined, features = sel_markers, assay = "RNA", cols="RdYlBu", dot.scale = 10) + theme(axis.text.x = element_text(angle=45, hjust=1))
print(p)

pdf(file.path(result_folder, "Fig_S5c.pdf"), width = 10, height = 5)
print(p)
dev.off()

```



# Supp Fig 6e


```{r}
library(GSVA)
gsva_score_file = file.path(data_storage_folder, file="Assembloids_SCT_CCadj_KinchenJasso_Stroma_signatures_GSVA.rds")
scores = readRDS(gsva_score_file)

rownames(scores) = gsub("KinchenJasso", "InVivo", rownames(scores))

for(ss in rownames(scores)) {
  scData.combined@meta.data[[ss]] = scores[ss, Cells(scData.combined)]
}

```



```{r, fig.height=4, fig.width=8}
p = DotPlot(scData.combined, features = sort(rownames(scores)), cols = "RdYlBu") + theme(axis.text.x = element_text(angle=45, hjust=1))
print(p)

pdf(file.path(result_folder, "Fig_S6e.pdf"), width = 8, height = 4)
print(p)
dev.off()
```


# Software versions

```{r}
sessionInfo()
```














